name: Compile TeX to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PDF file exists
        run: |
          if [ -f "Zohair's Resume.pdf" ]; then
            echo "PDF file already exists, exiting workflow."
            exit 0
          fi

      - name: Compile TeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Zohair's Resume.tex
          compiler: xelatex
          extra_fonts: |
            ./fonts/raleway/*.otf
            ./fonts/lato/*.ttf

      - name: Add and commit PDF
        run: |
          git config --global user.email "zohair.ul.hasan@gmail.com"
          git config --global user.name "GitHub Actions"
          git add "Zohair's Resume.pdf"
          git commit -m "Generate PDF from TeX"
          git push origin main
