name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  create_pdf:
    name: Create PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PDF file exists
        id: pdfExistsStep
        run: |
          if [ ! -f "Zohair's Resume.pdf" ]; then
            echo "PDF file does not exist."
            exit 1
          fi

      - name: Compile TeX to PDF
        if: steps.pdfExistsStep.conclusion == 'failiure'
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Zohair's Resume.tex

      - name: Add and commit PDF
        if: steps.pdfExistsStep.conclusion == 'failiure'
        run: |
          git config --global user.email "zohair.ul.hasan@gmail.com"
          git config --global user.name "GitHub Actions"
          git add "Zohair's Resume.pdf"
          git commit -m "Generate PDF from TeX"
          git push origin main
  deploy:
    needs: create_pdf
    name: Trigger Netlify Hook
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}
