name: Deploy PDF to Netlify

on:
  push:
    branches:
      - main

env:
  SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  deploy_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get deploy ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          DEPLOY_ID=$(curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
                       https://api.netlify.com/api/v1/sites/$SITE_ID/deploys | jq -r '.[0].id')

      - name: Deploy PDF to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOY_ID: ${{ env.DEPLOY_ID }}
        run: |
          curl -X PUT \
            -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
            -H "Content-Type: application/pdf" \
            --data-binary @"$GITHUB_WORKSPACE/Zohair's Resume.pdf" \
            "https://api.netlify.com/api/v1/sites/$SITE_ID/deploys/$DEPLOY_ID/files/public/Zohair's Resume.pdf"
